FROM golang:1.24-alpine

RUN apk add --no-cache git ca-certificates tzdata curl

RUN curl -sSfL https://raw.githubusercontent.com/air-verse/air/master/install.sh | sh -s -- -b /usr/local/bin

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

EXPOSE 8081

CMD ["air", "-c", ".air.toml"]