// backend/pkg/models/order.go
package models

import (
	"time"

	"go.mongodb.org/mongo-driver/bson/primitive"
)

// ============================================================================
// ORDER MODELS
// ============================================================================

// OrderItem represents a single line item (e.g., a ticket type and quantity).
type OrderItem struct {
	EventID    string `json:"eventId" db:"event_id" bson:"event_id"`
	EventTitle string `json:"eventTitle" db:"event_title" bson:"event_title"`
	TierName   string `json:"tierName" db:"tier_name" bson:"tier_name"`
	Quantity   int    `json:"quantity" db:"quantity" bson:"quantity"`
	Price      int    `json:"price" db:"unit_price" bson:"unit_price"`
	Subtotal   int    `json:"subtotal" db:"subtotal" bson:"subtotal"`
}

type OrderInitializationRequest struct {
	Email        string       `json:"email"`
	AmountInKobo int          `json:"amountInKobo"` // The calculated final amount
	Items        []OrderItem  `json:"items"`        // The full list of purchased items
	CustomerInfo CustomerInfo `json:"customerInfo"` // Contact details
	// Note: The 'reference' will be generated by the server for security
}

// CustomerInfo represents the billing and contact details collected from the form.
type CustomerInfo struct {
	FirstName string `json:"firstName" db:"first_name" bson:"first_name"`
	LastName  string `json:"lastName" db:"last_name" bson:"last_name"`
	Email     string `json:"email" db:"email" bson:"email"`
	Phone     string `json:"phone" db:"phone" bson:"phone"`
	City      string `json:"city" db:"city" bson:"city"`
	State     string `json:"state" db:"state" bson:"state"`
	Country   string `json:"country" db:"country" bson:"country"`
}

// Order represents the complete transaction record.
type Order struct {
	// Primary ID and User Links
	ID     primitive.ObjectID `json:"id" bson:"_id,omitempty"`
	UserID *int               `json:"userId" db:"user_id" bson:"user_id,omitempty"`

	// Transaction Data (from Paystack)
	Reference  string `json:"reference" db:"paystack_ref" bson:"reference"`
	Status     string `json:"status" db:"status" bson:"status"`
	AmountKobo int    `json:"amountKobo" db:"amount_kobo" bson:"amount_kobo"`
	FeeKobo    int    `json:"feeKobo" db:"paystack_fee_kobo" bson:"paystack_fee_kobo"`

	// Financial Totals
	Subtotal   int `json:"subtotal" db:"subtotal" bson:"subtotal"`
	ServiceFee int `json:"serviceFee" db:"service_fee" bson:"service_fee"`
	VATAmount  int `json:"vatAmount" db:"vat_amount" bson:"vat_amount"`
	FinalTotal int `json:"finalTotal" db:"final_total" bson:"final_total"`

	// Nested Data
	Customer CustomerInfo `json:"customer" bson:"customer"`
	Items    []OrderItem  `json:"items" bson:"items"`

	// Timestamps
	CreatedAt time.Time `json:"createdAt" db:"created_at" bson:"created_at"`
	UpdatedAt time.Time `json:"updatedAt" db:"updated_at" bson:"updated_at"`
}

// ============================================================================
// METADATA PARSING MODELS (For extracting data from Paystack custom_fields)
// ============================================================================

// OrderMetadata represents the structured metadata we expect from frontend
// This is what you'll parse from the custom_fields in Paystack metadata
type OrderMetadata struct {
	Customer CustomerInfo `json:"customer"`
	Items    []OrderItem  `json:"items"`
	Totals   OrderTotals  `json:"totals"`
}

// OrderTotals contains the financial breakdown sent in metadata
type OrderTotals struct {
	Subtotal     int `json:"subtotal"`
	ServiceFee   int `json:"serviceFee"`
	VATAmount    int `json:"vatAmount"`
	FinalTotal   int `json:"finalTotal"`
	AmountInKobo int `json:"amountInKobo"`
}